[theme]
primaryColor = "#2E86AB"
backgroundColor = "#F0F8FF"
secondaryBackgroundColor = "#E8F4FD"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableWebsocketCompression = false
maxUploadSize = 200

[browser]
gatherUsageStats = false
